In [1]:
import pandas as pd

In [42]:
df1 = pd.read_csv("C:\\Users\\amitm\\Downloads\\22. messy_sales_data.csv")

In [44]:
df = df1.copy()

In [45]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [7]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.width', 50)

In [8]:
df.shape

(106575, 15)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 106575 entries, 0 to 106574
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       106575 non-null  str
 1   CustomerID    106575 non-null  str
 2   CustomerName  106575 non-null  str
 3   City          104481 non-null  str
 4   Category      106575 non-null  str
 5   PaymentMode   103332 non-null  str
 6   Price         106575 non-null  str
 7   Quantity      106575 non-null  float64
 8   DiscountPct   106575 non-null  int64
 9   Rating        100129 non-null  float64
 10  OrderDate     102358 non-null  str
 11  CustomerAge   106575 non-null  float64
 12  Email         99176 non-null   str
 13  Phone         98117 non-null   str
 14  ReviewText    93200 non-null   str
dtypes: float64(3), int64(1), str(11)
memory usage: 12.2 MB

In [10]:
df.describe()

,Quantity,DiscountPct,Rating,CustomerAge
count,106575.000000,106575.000000,100129.000000,106575.000000
mean,2.066817,9.382125,3.409874,39.678893
std,1.387769,9.176865,1.306731,19.263288
min,-5.000000,0.000000,0.500000,0.000000
25%,1.000000,0.000000,2.600000,28.000000
50%,2.000000,10.000000,3.300000,38.000000
75%,3.000000,20.000000,4.100000,47.000000
max,5.000000,25.000000,9.900000,150.000000

In [11]:
df.describe(include='object')   # summary of categorical/string columns

C:\Users\amitm\AppData\Local\Temp\ipykernel_11764\3111763311.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')   # summary of categorical/string columns

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,OrderDate,Email,Phone,ReviewText
count,106575,106575,106575,104481,106575,103332,106575,102358,99176,98117,93200
unique,105000,9000,37440,56,35,24,88579,3367,39350,96653,14
top,ORD72254,CUST01057,Charvi Dara,hyderabad,BEAUTY,cash on delivery,966.86,01/03/2024,chakradhar.venkataraman@rediffmail.com,9783418336,worst product ever received damaged item
freq,3,27,29,2652,4499,5184,7,82,12,3,6785

In [12]:
df.dtypes

OrderID             str
CustomerID          str
CustomerName        str
City                str
Category            str
PaymentMode         str
Price               str
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate           str
CustomerAge     float64
Email               str
Phone               str
ReviewText          str
dtype: object

In [13]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName',
       'City', 'Category', 'PaymentMode',
       'Price', 'Quantity', 'DiscountPct',
       'Rating', 'OrderDate', 'CustomerAge',
       'Email', 'Phone', 'ReviewText'],
      dtype='str')

In [15]:
df.nunique()

OrderID         105000
CustomerID        9000
CustomerName     37440
City                56
Category            35
PaymentMode         24
Price            88579
Quantity            10
DiscountPct          6
Rating              91
OrderDate         3367
CustomerAge         66
Email            39350
Phone            96653
ReviewText          14
dtype: int64

In [16]:
df.isnull().sum()

OrderID             0
CustomerID          0
CustomerName        0
City             2094
Category            0
PaymentMode      3243
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
dtype: int64

In [33]:
df["Quantity"].mean().round(2)*100

np.float64(206.99999999999997)

In [34]:
df.isna().mean().round(3)*100

OrderID          0.0
CustomerID       0.0
CustomerName     0.0
City             2.0
Category         0.0
PaymentMode      3.0
Price            0.0
Quantity         0.0
DiscountPct      0.0
Rating           6.0
OrderDate        4.0
CustomerAge      0.0
Email            6.9
Phone            7.9
ReviewText      12.5
dtype: float64

In [37]:
df.DiscountPct.mean().round(2)

np.float64(9.38)

In [ ]:
# Rows where CustomerName is missing (probably none here, but to understand the pattern)
df[df['City'].isna()].head()

In [41]:
df[df['City'].isna()].head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
44,ORD60845,CUST00989,LAKSH SAINI,NaN,Clothings,NaN,1312.67,4.0,10,2.6,12 Mar 2024,35.0,laksh.saini@gmail.com,9170359225,Not satisfied poor quality
110,ORD20288,CUST01667,BALVEER RAM,NaN,Books,dc,344.35,2.0,0,3.3,11/02/2024,25.0,balveer.ram@gmail.com,9538529304,Product as described
130,ORD42875,CUST07659,Arjun Shukla,NaN,toys,cash on delivery,953.44,5.0,25,4.3,10 Dec 2024,47.0,arjun.shukla@gmail.com,9728243231,great service
177,ORD14310,CUST07857,Lavanya Bhargava,NaN,furniture,upi,Rs.1575.61,1.0,0,3.4,09/18/2023,22.0,lavanya.bhargava@hotmail.com,+91-9177552059,Average experience
195,ORD97450,CUST04620,Harrison Gala,NaN,Clothing,CREDIT CARD,873.31,1.0,5,1.2,2023-05-14,36.0,harrison.gala@hotmail.com,9163440026,Okayish product

In [49]:
# City missing -> fill with 'Unknown'
df["City"] = df['City'].fillna('Unknown')

In [50]:
df.City.isnull().sum()

np.int64(0)

In [64]:
mode_payment= df['PaymentMode'].mode()[0]

In [65]:
mode_payment

'UPI'

In [67]:
df['PaymentMode'] = df['PaymentMode'].fillna(df['PaymentMode'].mode()[0])

In [ ]:
# PaymentMode missing -> fill with mode (most common value)
mode_payment = df['PaymentMode'].mode()[0]
df['PaymentMode'] = df['PaymentMode'].fillna(mode_payment)
mode_payment

In [68]:
# Rating missing -> we'll fill with median (this is a numeric column, but might currently be a string, so
# we'll do the final missing-value fill step after Section 4 (type cleaning) below)
df.isna().sum()

OrderID             0
CustomerID          0
CustomerName        0
City                0
Category            0
PaymentMode         0
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
dtype: int64

In [69]:
df.duplicated().sum()   # how many fully duplicate rows there are

np.int64(1056)

In [74]:
df[df.duplicated(keep=False)]

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
81,ORD61902,CUST03914,Yash Sawhney,Calcutta,Book,UPI,1090.48,3.0,5,3.5,08/14/2023,27.0,yash.sawhney@gmail.com,9544764196,Okayish product
121,ORD19515,CUST03317,Balendra Lata,madras,beauty,Net Banking,"₹1,119.91",1.0,0,1.3,18-10-2023,37.0,balendra.lata@yahoo.com,+91-9312070442,delivery was late
130,ORD42875,CUST07659,Arjun Shukla,Unknown,toys,cash on delivery,953.44,5.0,25,4.3,10 Dec 2024,47.0,arjun.shukla@gmail.com,9728243231,great service
174,ORD97258,CUST04413,Jatin Borra,Pune,Toy,COD,₹738.54,3.0,25,4.2,2024-12-27,24.0,jatin.borra@hotmail.com,9164615469,Good product loved it
230,ORD88850,CUST05230,Falan Bumb,Lucknow,GROCERY,net banking,970.54,2.0,20,2.4,23/08/2023,50.0,falan.bumb@outlook.com,9680305954,Excellent!!! will buy again
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106224,ORD20702,CUST04842,Turvi Lad,kolkata,toys,UPI,905.00,3.0,15,4.5,04 Jan 2023,38.0,turvi.lad@gmail.com,9772902764,Excellent!!! will buy again
106266,ORD57327,CUST06398,Sai Misra,JAIPUR,BOOKS,Credit Card,933.80,1.0,0,1.9,NaN,21.0,sai.misra@outlook.com,9675353405,Amazing quality!!!
106399,ORD52908,CUST00065,Darsh Rau,LUCKNOW,ELECTRONICS,Upi,1131.14,2.0,5,3.0,06/05/2023,48.0,darsh.rau@gmail.com,9657689492,Not satisfied poor quality
106434,ORD17717,CUST00227,ZAYYAN SRIDHAR,CALCUTTA,furniture,cash on delivery,934.25,1.0,15,4.8,04/24/2024,38.0,zayyan.sridhar@rediffmail.com,9168130141,Not satisfied poor quality
106560,ORD68829,CUST01971,AARAV BOBAL,Bombay,Beauty,CREDIT CARD,-2040.44,4.0,15,3.9,2023-03-19,45.0,NaN,+91-9795734459,great service

In [73]:
df[df.duplicated(keep=False)].sort_values('OrderID').head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
12509,ORD10011,CUST05549,Dominic Nadig,Mumbai,grocery,Debit Card,986.17,2.0,10,1.1,09/23/2023,31.0,dominic.nadig@yahoo.com,9531043479,delivery was late
46621,ORD10011,CUST05549,Dominic Nadig,Mumbai,grocery,Debit Card,986.17,2.0,10,1.1,09/23/2023,31.0,dominic.nadig@yahoo.com,9531043479,delivery was late
54945,ORD100260,CUST08013,Krisha Mann,bangalore,Sport,CC,492.31,1.0,25,5.0,05/07/2023,36.0,krisha.mann@gmail.com,9240809583,Will not recommend
19142,ORD100260,CUST08013,Krisha Mann,bangalore,Sport,CC,492.31,1.0,25,5.0,05/07/2023,36.0,krisha.mann@gmail.com,9240809583,Will not recommend
77714,ORD100271,CUST01032,SIYA BORAH,Chennai,GROCERY,cc,4020.00,1.0,20,1.6,02/12/2023,18.0,siya.borah@rediffmail.com,9255516690,Not satisfied poor quality

In [75]:
df = df.drop_duplicates()

In [76]:
df.shape

(105519, 15)

In [77]:
# Check for duplicate IDs in the OrderID column (business rule: OrderID must be unique)
df['OrderID'].duplicated().sum()

np.int64(519)

In [78]:
dup_order_ids = df[df['OrderID'].duplicated(keep=False)].sort_values('OrderID')
dup_order_ids.head(10)

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
32426,ORD100005,CUST05579,David Bal,Delhi,Grocery,Net Banking,863.53,1.0,10,1.6,04/12/2023,20.0,david.bal@gmail.com,9995203533,Okayish product
20951,ORD100005,CUST05579,David Bal,Delhi,Grocery,Net Banking,863.53,1.0,10,3.1,04/12/2023,20.0,david.bal@gmail.com,9995203533,Okayish product
96637,ORD100103,CUST06331,Neelima Misra,new delhi,books,CC,826.34,3.0,5,2.9,06 Jun 2024,55.0,neelima.misra@rediffmail.com,9501612029,Amazing quality!!!
32568,ORD100103,CUST06331,Neelima Misra,new delhi,books,CC,826.34,1.0,5,2.8,06 Jun 2024,55.0,neelima.misra@rediffmail.com,9501612029,Amazing quality!!!
42271,ORD100231,CUST02969,SIMON MANGAL,Delhi,FURNITURE,cc,1689.30,4.0,5,1.2,29 Apr 2023,18.0,simon.mangal@yahoo.com,9301415018,worst product ever received damaged item
73117,ORD100231,CUST02969,SIMON MANGAL,Delhi,FURNITURE,cc,1689.30,3.0,5,4.8,29 Apr 2023,18.0,simon.mangal@yahoo.com,9301415018,worst product ever received damaged item
64479,ORD100468,CUST03692,ONKAR VOHRA,CALCUTTA,BOOKS,credit_card,641.28,1.0,25,1.6,14 Jan 2023,48.0,onkar.vohra@rediffmail.com,9508185838,Okayish product
81799,ORD100468,CUST03692,ONKAR VOHRA,CALCUTTA,BOOKS,credit_card,641.28,2.0,25,2.5,14 Jan 2023,48.0,onkar.vohra@rediffmail.com,9508185838,Okayish product
26621,ORD100643,CUST02939,Varenya Lata,Delhi,BEAUTY,UPI,Rs.544.40,1.0,25,4.6,24-08-2023,18.0,varenya.lata@gmail.com,9153264678,Amazing quality!!!
87213,ORD100643,CUST02939,Varenya Lata,Delhi,BEAUTY,UPI,Rs.544.40,4.0,25,4.2,24-08-2023,18.0,varenya.lata@gmail.com,9153264678,Amazing quality!!!

In [82]:
df['CustomerName'].unique()[1:35000:100]

<StringArray>
[        'Siddharth Sha',
           'Indali Kala',
       'Chandresh Sarma',
           'nikita kade',
         'Wahab Agarwal',
         'Saksham Jaggi',
          'Jacob Prabhu',
           'Abeer Golla',
      'ayushman chander',
    '  Brijesh Mander  ',
 ...
        'WIDISHA PILLAI',
         'aachal bhalla',
    '  Viraj Bhargava  ',
   '  eiravati bansal  ',
 '  Panini Srivastava  ',
         'azad bhandari',
     ' Balveer Deshmukh',
       '  Anya Sangha  ',
         ' Lucky Sachar',
      'VIHAAN CHOUDHURY']
Length: 350, dtype: str

In [87]:
df['CustomerName'].str.strip().str.title()

0               Chaitanya Mane
1                Siddharth Sha
2         Nathaniel Chatterjee
3            Pranit Contractor
4           Hemang Chakraborty
                  ...
106570                  Max Om
106571            Charan Manne
106572             Isaiah Wali
106573          Ladli Nazareth
106574               Yatin Rao
Name: CustomerName, Length: 105519, dtype: str

In [88]:
df["new_name"] = df["CustomerName"].str.strip().str.title()

In [91]:
df["new_name"].unique()[:10]

<StringArray>
[      'Chaitanya Mane',        'Siddharth Sha',
 'Nathaniel Chatterjee',    'Pranit Contractor',
   'Hemang Chakraborty',          'Ishaan Nair',
       'Tara Nagarajan',          'Waida Kapur',
          'Turvi Dugar',          'Kevin Amble']
Length: 10, dtype: str

In [92]:
df['City'].unique()

<StringArray>
[ 'bangalore',      'DELHI',    'chennai',
    'Jaipur ',    'Amdavad',  'New Delhi',
  'new delhi',    'Kolkata',  'hyderabad',
     'mumbai',   ' Lucknow',    'LUCKNOW',
     'jaipur',  'Bengaluru',   'Calcutta',
     'MADRAS',  'bengaluru',     'Bombay',
      'Poona',    'CHENNAI',       'pune',
   'CALCUTTA',    'Lucknow',    'kolkata',
  'AHMEDABAD',    ' Mumbai',  'Ahmedabad',
       'PUNE',     'Jaipur',      'delhi',
    'KOLKATA',     'Mumbai',    'Unknown',
    ' Delhi ',  'HYDERABAD',   'calcutta',
     'bombay',    'amdavad',  'NEW DELHI',
     'JAIPUR',  'ahmedabad',      'poona',
     'Madras',  'Bangalore',    'Chennai',
    'lucknow',   'Banglore',     'madras',
  'BANGALORE',   'mumbai  ',  'Hyderabad',
     'BOMBAY',       'Pune',      'Delhi',
   'banglore', ' Hyderabad',     'MUMBAI']
Length: 57, dtype: str